const FETCH_ARTICLE = "FETCH_ARTICLE";
const FETCH_ARTICLES = "FETCH_ARTICLES";
const CREATE_ARTICLE = "CREATE_ARTICLE";
const DELETE_ARTICLE = "DELETE_ARTICLE";


export { FETCH_ARTICLE, FETCH_ARTICLES, CREATE_ARTICLE, DELETE_ARTICLE};
